#!/bin/sh -e

package=xul-ext-ui2pbrowser-branding
if [ "$1" = "upgrade" ] || [ "$1" = "install" ] ; then
    dpkg-divert --package "$package" --divert /usr/share/applications/ui2pbrowser.desktop.diverted --rename /usr/share/applications/ui2pbrowser.desktop
fi

#DEBHELPER#
